import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../../core/api_error.dart';
import '../../providers.dart';

/// A4 print-sheet preview. The PDF is generated by the backend (vector QR,
/// crop marks, print-at-100% instructions) — the app only previews, prints,
/// and shares it. No business logic in the client.
class StickerPreviewScreen extends ConsumerWidget {
  const StickerPreviewScreen({super.key, required this.vehicleId});

  final String vehicleId;

  Future<Uint8List> _fetchPdf(WidgetRef ref) async {
    try {
      final repo = ref.read(vehicleRepositoryProvider);
      final vehicle = await repo.get(vehicleId);
      final file = await repo.downloadStickerPdf(vehicle.id, vehicle.publicToken);
      return await file.readAsBytes();
    } on ApiException catch (e) {
      throw Exception(e.message);
    }
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('A4 Sticker Sheet'),
        actions: [
          IconButton(
            tooltip: 'Share PDF',
            icon: const Icon(Icons.ios_share),
            onPressed: () async {
              try {
                final bytes = await _fetchPdf(ref);
                final dir = await getTemporaryDirectory();
                final path = '${dir.path}/pingmycar-sticker-a4.pdf';
                await File(path).writeAsBytes(bytes, flush: true);
                await Share.shareXFiles([XFile(path)]);
              } catch (e) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e')));
                }
              }
            },
          ),
        ],
      ),
      // Backend-generated PDF; PdfPreview renders it and offers system
      // print. The sheet already carries crop marks and the
      // print-at-100% instruction.
      body: PdfPreview(
        canChangePageFormat: false,
        build: (format) => _fetchPdf(ref),
        pdfFileName: 'pingmycar-sticker-a4.pdf',
      ),
    );
  }
}
