import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import '../../core/api_error.dart';
import '../../providers.dart';
import '../components/components.dart';

/// A4 print-sheet preview. The PDF is generated by the backend (vector QR,
/// crop marks, print-at-100% instructions) — the app only previews, prints,
/// and shares it. No business logic in the client.
class StickerPreviewScreen extends ConsumerStatefulWidget {
  const StickerPreviewScreen({super.key, required this.vehicleId});

  final String vehicleId;

  @override
  ConsumerState<StickerPreviewScreen> createState() => _StickerPreviewScreenState();
}

class _StickerPreviewScreenState extends ConsumerState<StickerPreviewScreen> {
  bool _sharing = false;

  Future<Uint8List> _fetchPdf() async {
    try {
      final repo = ref.read(vehicleRepositoryProvider);
      final vehicle = await repo.get(widget.vehicleId);
      final file = await repo.downloadStickerPdf(vehicle.id, vehicle.publicToken);
      return await file.readAsBytes();
    } on ApiException catch (e) {
      throw Exception(e.message);
    }
  }

  Future<void> _share() async {
    if (_sharing) return;
    setState(() => _sharing = true);
    try {
      final bytes = await _fetchPdf();
      final dir = await getTemporaryDirectory();
      final path = '${dir.path}/pingmycar-sticker-a4.pdf';
      await File(path).writeAsBytes(bytes, flush: true);
      await Share.shareXFiles([XFile(path)]);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(e.toString().replaceFirst('Exception: ', ''))),
        );
      }
    } finally {
      if (mounted) setState(() => _sharing = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final c = AppColors.of(context);
    final t = Theme.of(context).textTheme;
    return Scaffold(
      appBar: AppBar(
        title: const Text('Print stickers'),
        actions: [
          _sharing
              ? const Padding(
                  padding: EdgeInsets.all(14),
                  child: SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)),
                )
              : IconButton(tooltip: 'Share PDF', icon: const Icon(Icons.ios_share_outlined), onPressed: _share),
          const SizedBox(width: Space.xs),
        ],
      ),
      body: Column(
        children: [
          Container(
            width: double.infinity,
            margin: const EdgeInsets.fromLTRB(Space.page, 0, Space.page, Space.sm),
            padding: const EdgeInsets.all(Space.sm),
            decoration: BoxDecoration(color: c.primarySoft, borderRadius: BorderRadius.circular(Radii.md)),
            child: Row(
              children: [
                Icon(Icons.straighten_outlined, size: 18, color: c.primary),
                const SizedBox(width: Space.xs),
                Expanded(
                  child: Text(
                    'Print at 100% / Actual size on A4, then cut along the crop marks.',
                    style: t.bodySmall?.copyWith(color: c.ink),
                  ),
                ),
              ],
            ),
          ),
          // Backend-generated PDF; PdfPreview renders it and offers system
          // print. The sheet already carries crop marks and instructions.
          Expanded(
            child: PdfPreview(
              canChangePageFormat: false,
              canChangeOrientation: false,
              canDebug: false,
              build: (format) => _fetchPdf(),
              pdfFileName: 'pingmycar-sticker-a4.pdf',
              loadingWidget: const Center(child: CircularProgressIndicator()),
              onError: (context, error) => ErrorState(
                error: ApiException(ApiErrorKind.unknown, error.toString().replaceFirst('Exception: ', '')),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
